# Generated by Django 3.1.2 on 2020-10-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='cards',
            options={'verbose_name': 'Карточки потолков', 'verbose_name_plural': 'Карточки потолков'},
        ),
    ]
