# Generated by Django 3.1.2 on 2020-11-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_gallery_newclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='text',
        ),
        migrations.AddField(
            model_name='testimonials',
            name='testimonialImg',
            field=models.ImageField(default='', upload_to='testimonials/'),
        ),
    ]
