# Generated by Django 3.1.2 on 2020-11-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20201106_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSalePotolok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('potlok', models.CharField(max_length=35)),
            ],
        ),
    ]
