# Generated by Django 3.1.2 on 2020-11-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_newsalepotolok'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsalepotolok',
            old_name='potlok',
            new_name='potolok',
        ),
    ]
