# Generated by Django 3.1.2 on 2020-11-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20201115_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newclient',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
